paragony/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'paragony.views.homepage'),

    url(r'^accounts/create_user/$', 'paragony.views.create_user'),
    url(r'^accounts/login/$', 'paragony.views.login'),
    url(r'^accounts/auth/$', 'paragony.views.auth_view'),
    url(r'^accounts/logout/$', 'paragony.views.logout'),

    url(r'^accounts/loggedin/settings/$', 'paragony.views.settings'),
    url(r'^accounts/loggedin/delete_account/$', 'paragony.views.delete_account'),
    url(r'^accounts/loggedin/$', 'receipts.views.loggedin'),
    url(r'^accounts/loggedin/add_item/$', 'receipts.views.add_item'),
    url(r'^accounts/loggedin/edit/(?P<item_id>\d+)/$', 'receipts.views.edit_item'),
    url(r'^accounts/loggedin/delete_item/(?P<item_id>\d+)/$', 'receipts.views.delete_item'),
    url(r'^accounts/loggedin/delete_image/(?P<item_id>\d+)/(?P<img_type>[\w\-]+)/$', 'receipts.views.delete_image'),
]

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

receipts/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class Items(models.Model):
    CATEGORY = (
        ('', 'Wybierz'),
        ('moda', 'Moda'),
        ('elektronika', 'Elektronika'),
        ('dom_ogrod', 'Dom & Ogród'),
        ('zdrowie_uroda', 'Zdrowie & Uroda'),
        ('motoryzacja', 'Motoryzacja'),
        ('sport', 'Sport'),
        ('rozrywka', 'Rozrywka'),
        ('bizuteria', 'Biżuteria'),
        ('narzedzia', 'Narzędzia'),
        ('inne', 'Inne')
    )

    name = models.CharField(max_length=150)
    warranty = models.DateField()
    category = models.CharField(choices=CATEGORY, max_length=40)
    img_item = models.FileField(upload_to="images/")
    img_receipt = models.FileField(upload_to="images/")
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.name

receipts/forms.py
#-*- coding: utf-8 -*-
from django import forms
from models import Items

class ItemsForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "required form-control", "minlength": "2"}), label="Nazwa produktu")
    warranty = forms.CharField(widget=forms.DateInput(attrs={"class": "required dateISO form-control warranty_input", "readonly": ""}), label="Koniec gwarancji")
    category = forms.ChoiceField(choices=(Items.CATEGORY), widget=forms.Select(attrs={'class': 'required form-control category_input'}), label="Kategoria")
    img_item = forms.FileField(required=False, label="Zdjęcie produktu")
    img_receipt = forms.FileField(required=False, label="Zdjęcie paragonu")

    class Meta:
        model = Items
        fields = ('name', 'warranty', 'category', 'img_item', 'img_receipt')

receipts/views.py
#-*- coding: utf-8 -*-
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.context_processors import csrf
import copy
from receipts.models import Items
from forms import ItemsForm
from sorethumb.djangothumbnail import DjangoThumbnail
from sorethumb.filters.defaultfilters import ThumbnailFilter, FixedWidthFilter
from sorethumb.templatetags import sorethumb
import os
from django.conf import settings


class SmallThumb(DjangoThumbnail):
    try:
        name = 'item_thumb'
        quality = 100
        filters = [ThumbnailFilter(220, 220),
                   FixedWidthFilter(220, no_upscale=False)]
    except Exception as e:
        print e


def loggedin(request):
    try:
        item_form = ItemsForm()
        args = {}
        args.update(csrf(request))
        args['item_form'] = item_form
        if request.user.is_authenticated():
            args['user'] = request.user

            if request.GET.get('sort', '') == 'old':
                args['items'] = Items.objects.filter(user=args['user']).order_by('-id')
            elif request.GET.get('sort', '') == 'warranty':
                args['items'] = Items.objects.filter(user=args['user']).order_by('warranty')
            else:
                args['items'] = Items.objects.filter(user=args['user'])

        return render_to_response('loggedin.html', args)
    except Exception as e:
        print e


def add_item(request):
    try:
        if request.method == 'POST':
            item_form = ItemsForm(request.POST, request.FILES)
            if item_form.is_valid():
                new_item = item_form.save(commit=False)
                user = request.user
                new_item.user = user
                new_item.save()
                return HttpResponseRedirect('/accounts/loggedin/')
            else:
                args = {}
                args['message'] = "Dodanie przedmiotu zakończone niepowodzeniem."
                args['type_message'] = "negative"
                args['item_form'] = item_form
                return render_to_response('edit.html', args, context_instance=RequestContext(request))
        else:
            item_form = ItemsForm()
            return render_to_response('edit.html', {'item_form': item_form}, context_instance=RequestContext(request))
    except Exception as e:
        print e


def delete_image(request, item_id, img_type, return_edit=True):
    try:
        item = Items.objects.get(id=item_id)
        owner = item.user.id
        if owner == request.user.id:
            if img_type == 'img_item':
                # MyDevil: os.remove(settings.BASE_DIR + '/public' + sorethumb.sorethumb(item.img_item, "item_thumb"))
                os.remove(settings.BASE_DIR + sorethumb.sorethumb(item.img_item, "item_thumb"))
                item.img_item.delete(save=False)

            if img_type == 'img_receipt':
                # MyDevil: os.remove(settings.BASE_DIR + '/public' + sorethumb.sorethumb(item.img_receipt, "item_thumb"))
                os.remove(settings.BASE_DIR + sorethumb.sorethumb(item.img_receipt, "item_thumb"))
                item.img_receipt.delete(save=False)

            item.save()

        if return_edit:
            return HttpResponseRedirect('/accounts/loggedin/edit/%s/' % item_id)
    except Exception as e:
        print e


def delete_item(request, item_id, return_loggedin=True):
    try:
        item = Items.objects.get(id=item_id)
        owner = item.user.id
        if owner == request.user.id:
            if item.img_item:
                delete_image(request, item_id, 'img_item', return_edit=False)
            if item.img_receipt:
                delete_image(request, item_id, 'img_receipt', return_edit=False)
            item.delete()

        if return_loggedin:
            return HttpResponseRedirect('/accounts/loggedin/')
    except Exception as e:
        print e


def edit_item(request, item_id):
    try:
        item = Items.objects.get(id=item_id)
        item_form = ItemsForm(instance=item)
        args = {}

        if request.method == 'POST':
            item2 = copy.copy(item)

            form = ItemsForm(request.POST, request.FILES, instance=item)
            if form.is_valid():
                ed_item = form.save(commit=False)

                if ed_item.img_item and item2.img_item:
                    if ed_item.img_item.url != item2.img_item.url:
                        delete_image(request, item_id, 'img_item', return_edit=False)
                if ed_item.img_receipt and item2.img_receipt:
                    if ed_item.img_receipt.url != item2.img_receipt.url:
                        delete_image(request, item_id, 'img_receipt', return_edit=False)

                ed_item.save()
                return HttpResponseRedirect('/accounts/loggedin/')
            else:
                args['message'] = "Edycja przedmiotu zakończone niepowodzeniem."
                args['type_message'] = "negative"

        owner = item.user.id
        if owner == request.user.id:
            args.update(csrf(request))
            args['item_form'] = item_form
            args['item_id'] = item_id
            return render(request, 'edit.html', args)
        else:
            return HttpResponseRedirect('/accounts/loggedin/')
    except Exception as e:
        print e

receipts/templates/edit.html
{% extends "main_loggedin.html" %}
{% load static %}
{% load sorethumb %}
{% block receipts %}

    <div class="container">
        {% if message and type_message %}
            <h2 class="{{ type_message }}-message">{{ message }}</h2>
        {% endif %}
        <div class="edit">
            <form method="post" enctype="multipart/form-data" id="edit_form" class="form-inline">{% csrf_token %}
                <div class="form_section  col-lg-12">
                    <div class="txt_input" style="">
                        <p><label>Nazwa produktu: </label>{{ item_form.name }}<i class="glyphicon glyphicon-font form-control-feedback"></i></p>
                        <p><label>Koniec gwarancji: </label>{{ item_form.warranty }}<i class="glyphicon glyphicon-calendar form-control-feedback"></i></p>
                        <p><label>Kategoria: </label>{{ item_form.category }}<i class="glyphicon glyphicon-list-alt form-control-feedback"></i></p>

                    </div>
                </div>

                <div class="form_section  col-lg-12">
                    {% if item_form.img_item.value %}
                        <img src="{{ item_form.img_item.value|sorethumb:"item_thumb" }}">
                        <div class="new_img_input">
                            <h4>Zdjęcie produktu:</h4>
                            <p><a class="btn btn-primary" target="_blank" href="{{ item_form.img_item.value.url }}">Otwórz zdjęcie w pełnym rozmiarze</a></p>
                            <p><a class="btn btn-danger" href="/accounts/loggedin/delete_image/{{ item_id }}/img_item/">Usuń zdjęcie</a></p>
                            <label>Zamień na inne zdjęcie:</label>
                            <input id="id_img_item" name="img_item" type="file">
                        </div>

                    {% else %}
                        <div class="txt_input">
                            <p><label>Zdjęcie produktu:</label>
                            <input id="id_img_item" name="img_item" type="file"></p>
                        </div>
                    {% endif %}
                </div>

                <div class="form_section  col-lg-12">
                    {% if item_form.img_receipt.value %}
                        <img src="{{ item_form.img_receipt.value|sorethumb:"item_thumb" }}">
                        <div class="new_img_input">
                            <h4>Zdjęcie paragonu:</h4>
                            <p><a class="btn btn-primary" target="_blank"  href="{{ item_form.img_receipt.value.url }}">Otwórz zdjęcie w pełnym rozmiarze</a></p>
                            <p><a class="btn btn-danger" href="/accounts/loggedin/delete_image/{{ item_id }}/img_receipt/">Usuń zdjęcie</a></p>
                            <label>Zamień na inne zdjęcie:</label>
                            <input id="id_img_receipt" name="img_receipt" type="file">
                        </div>
                    {% else %}
                        <div class="txt_input">
                            <p>
                            <label>Zdjęcie paragonu:</label>
                            <input id="id_img_receipt" name="img_receipt" type="file"></p>
                        </div>
                    {% endif %}
                </div>

                <div class="col-lg-12">
                    <div class="save_delete">
                        <input type="submit" value="Zapisz" class="btn btn-success">
                        <a href="/accounts/loggedin/delete_item/{{ item_id }}/" class="btn btn-danger">Usuń produkt</a>
                    </div>
                </div>
                <a href="/accounts/loggedin/" class="btn btn-primary back_link">Powrót do wszystkich przedmiotów</a>
            </form>
        </div>
    </div>


    <script>
        $(function() {
            $( "#id_warranty" ).datepicker({
                changeMonth: true,
                changeYear: true
            });
            $( "#id_warranty" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
            $( "#id_warranty" ).datepicker( $.datepicker.regional[ "pl" ] );

            $("#edit_form").validate();
        });
    </script>

{% endblock %}

receipts/templates/loggedin.html
{% extends "main_loggedin.html" %}
{% load static %}
{% load sorethumb %}
{% block receipts %}

    {% if user.is_authenticated %}

        <div class="sort_options">
            <nav class="navbar">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
                    <ul class="nav navbar-nav">
                        <li class="nav-item"><a class="nav-link sort-txt">sortuj</a></li>
                        <li class="nav-item"><a class="nav-link" href="/accounts/loggedin/">najnowsze</a></li>
                        <li class="nav-item"><a class="nav-link" href="/accounts/loggedin/?sort=old">najstarsze</a></li>
                        <li class="nav-item"><a class="nav-link" href="/accounts/loggedin/?sort=warranty">koniec gwarancji</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/accounts/loggedin/settings/">ustawienia</a></li>
                        <li><a href="/accounts/logout/">wyloguj</a></li>
                    </ul>
                </div>
            </nav>
        </div>


        <div id="item_grid">
            <div class="box">
                <a href="add_item/">
                    <div class="new-item">
                        <img src="{% static 'img/plus.png' %}">
                    </div>
                    <div class="box_content">
                        <p>Dodaj nowy produkt</p>
                    </div>
                </a>
            </div>

            {% for item in items %}
                <a href="edit/{{ item.id }}/">
                    <div class="box">
                        {% if item.img_item %}
                            <img src="{{ item.img_item|sorethumb:"item_thumb" }}">
                        {% else %}
                            <img src="{% static 'img/category_icon/' %}{{ item.category }}.jpg">
                        {% endif %}

                        <div class="box_content">
                            <p>{{ item.name }}</p>
                            <hr>
                            <p>Koniec gwarancji: {{ item.warranty | date:"d.m.Y" }}</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>


        <script src="{% static 'js/jquery.waterfall.js' %}"></script>
        <script>
            $("#item_grid").waterfall({
                itemClass: ".box",
                minColCount: 1,
                spacingHeight: 14,
                spacingWidth: 14,
                resizeable: true,
            });


            var ml = ($(window).width() % 234) / 2;
            var mr = ml + 14;
            $('.sort_options').css({
                "margin-left": ml,
                "margin-right": mr
            });

            window.onresize = function() {
                var ml = ($(window).width() % 234) / 2;
                var mr = ml + 14;
                $('.sort_options').css({
                    "margin-left": ml,
                    "margin-right": mr
                 });
            };
        </script>

    {% else %}
        <h3 class="negative-message">Dostęp tylko dla zalogowanych użytkowników, <a href="/accounts/login/">zaloguj się</a></h3>
    {% endif %}

{% endblock %}

receipts/templates/main_loggedin.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" media="screen">
    <script type='text/javascript' src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/bootstrap.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.validate.js' %}"></script>

    <!-- jquery UI - Datepicker -->
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/datepicker-pl.js' %}"></script>

    <link href="{% static 'css/style.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="screen">
</head>
<body>

    <header>
        <div class="row loggedin_logo">
            <a href="/accounts/loggedin/">
                <img src="{% static 'img/receipt.png' %}">
                <span>paragonik</span>
            </a>
        </div>
    </header>


    {% block receipts %}
    {% endblock %}


</body>
</html>